### ISSUE TITLE
SIM cards for GSM phones

### ISSUE THREAD

**Issue by edbek** [popovec/oseid#2]
Can this project be used to emulate SIM cards for GSM phones?

**Comment by popovec** [comment]
This project is aimed at emulating the MyEID smart card. Part of the code in this project is also applicable for GSM SIM card emulation (mainly communication between card and card reader, APDU parsing, file system service, ISO7816 functions, etc.). but full emulation of the SIM card in this project is not implemented and the project does not even set such a goal.
